/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design system del nuevo diseño
        'surface':                    '#001330',
        'inverse-on-surface':         '#002f66',
        'surface-container-lowest':   '#000e26',
        'secondary-fixed-dim':        '#acc7ff',
        'primary-container':          '#884800',
        'surface-dim':                '#001330',
        'tertiary-fixed-dim':         '#c6c6c7',
        'surface-tint':               '#ffb77d',
        'on-tertiary-fixed-variant':  '#454747',
        'error-container':            '#93000a',
        'on-surface':                 '#d7e2ff',
        'on-surface-variant':         '#c2c6d4',
        'inverse-surface':            '#d7e2ff',
        'tertiary':                   '#c6c6c7',
        'on-secondary-fixed':         '#001a40',
        'on-primary-fixed':           '#2f1500',
        'inverse-primary':            '#904d00',
        'on-primary':                 '#4d2600',
        'on-tertiary-container':      '#cfd0d0',
        'surface-variant':            '#00336e',
        'tertiary-container':         '#575959',
        'on-secondary':               '#002f67',
        'on-background':              '#d7e2ff',
        'on-secondary-container':     '#bcd1ff',
        'on-error-container':         '#ffdad6',
        'surface-container':          '#001f46',
        'surface-container-low':      '#001b3f',
        'secondary-fixed':            '#d7e2ff',
        'on-tertiary-fixed':          '#1a1c1c',
        'background':                 '#001330',
        'primary-fixed':              '#ffdcc3',
        'tertiary-fixed':             '#e2e2e2',
        'error':                      '#ffb4ab',
        'secondary':                  '#acc7ff',
        'primary':                    '#ffb77d',
        'on-primary-container':       '#ffc496',
        'primary-fixed-dim':          '#ffb77d',
        'on-primary-fixed-variant':   '#6e3900',
        'on-secondary-fixed-variant': '#004491',
        'on-error':                   '#690005',
        'outline-variant':            '#424752',
        'surface-container-highest':  '#00336e',
        'surface-container-high':     '#002a5c',
        'outline':                    '#8c909e',
        'surface-bright':             '#003876',
        'on-surface-bright':          '#ffffff',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg:      '2rem',
        xl:      '3rem',
        full:    '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
        sans:     ['Manrope', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
