/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design system — paleta azul más clarita
        'surface':                    '#0a2a5e',
        'inverse-on-surface':         '#cfe0ff',
        'surface-container-lowest':   '#061d4a',
        'secondary-fixed-dim':        '#b8d4ff',
        'primary-container':          '#884800',
        'surface-dim':                '#0a2a5e',
        'tertiary-fixed-dim':         '#c6c6c7',
        'surface-tint':               '#ffb77d',
        'on-tertiary-fixed-variant':  '#454747',
        'error-container':            '#93000a',
        'on-surface':                 '#e8f0ff',
        'on-surface-variant':         '#d0d8ee',
        'inverse-surface':            '#d7e2ff',
        'tertiary':                   '#c6c6c7',
        'on-secondary-fixed':         '#001a40',
        'on-primary-fixed':           '#2f1500',
        'inverse-primary':            '#904d00',
        'on-primary':                 '#4d2600',
        'on-tertiary-container':      '#cfd0d0',
        'surface-variant':            '#1a4a8a',
        'tertiary-container':         '#575959',
        'on-secondary':               '#002f67',
        'on-background':              '#e8f0ff',
        'on-secondary-container':     '#cfe0ff',
        'on-error-container':         '#ffdad6',
        'surface-container':          '#0f3570',
        'surface-container-low':      '#0c2e64',
        'secondary-fixed':            '#d7e2ff',
        'on-tertiary-fixed':          '#1a1c1c',
        'background':                 '#0a2a5e',
        'primary-fixed':              '#ffdcc3',
        'tertiary-fixed':             '#e2e2e2',
        'error':                      '#ffb4ab',
        'secondary':                  '#7eb8ff',
        'primary':                    '#ffb77d',
        'on-primary-container':       '#ffc496',
        'primary-fixed-dim':          '#ffb77d',
        'on-primary-fixed-variant':   '#6e3900',
        'on-secondary-fixed-variant': '#004491',
        'on-error':                   '#690005',
        'outline-variant':            '#2e5490',
        'surface-container-highest':  '#1a4a8a',
        'surface-container-high':     '#143d7a',
        'outline':                    '#5a85c0',
        'surface-bright':             '#1e5299',
        'on-surface-bright':          '#ffffff',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg:      '2rem',
        xl:      '3rem',
        full:    '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
        sans:     ['Manrope', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
